name: ScrapBukkit
main: com.dinnerbone.bukkit.scrap.ScrapBukkit
version: 0.1
commands:
  clear:
    description: Clears your inventory
    usage: /clear
  give:
    description: Give you or give out items
    usage: /give
  tp:
    description: Teleports you or someone to somewhere
    usage: /tp
  tphere:
    description: Tp here
    usage: /tphere
  time:
    description: Sets/shows the current time
    usage: /time
  take:
    description: Remove an item from your inventory
    usage: /take